language: python
python:
  - "3.7"
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - python setup.py test